theme: jekyll-theme-minimal
title: Room no. 308
description: The room of our random experiments
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
